#!/bin/bash
# OpenEuroLLM Cluster Environment Installer
# Usage: curl -sSL https://raw.githubusercontent.com/ORG/REPO/main/cluster-config/install.sh | bash
#    or: bash cluster-config/install.sh  (local install)

set -e

GITHUB_BASE_URL="https://raw.githubusercontent.com/OpenEuroLLM/clusterenv/main"
INSTALL_DIR="$HOME/.openeurollm-env"
CLUSTERS=(lumi leonardo jupiter juwels local)

# Detect if running locally (script directory contains the config files)
# Handle both bash and zsh, and both sourcing and direct execution
if [ -n "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
elif [ -n "$ZSH_VERSION" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${(%):-%x}")" && pwd)"
else
    SCRIPT_DIR=""
fi

LOCAL_MODE=false
if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/common.sh" ] && [ -d "$SCRIPT_DIR/clusters" ]; then
    LOCAL_MODE=true
fi

echo "Installing OpenEuroLLM cluster environment..."

# Create installation directory
mkdir -p "$INSTALL_DIR/clusters"

# Copy or download configuration files
if [ "$LOCAL_MODE" = true ]; then
    echo "Installing from local files..."
    cp "$SCRIPT_DIR/common.sh" "$INSTALL_DIR/common.sh"
    cp "$SCRIPT_DIR/update.sh" "$INSTALL_DIR/update.sh"
    chmod +x "$INSTALL_DIR/update.sh"
    for cluster in "${CLUSTERS[@]}"; do
        cp "$SCRIPT_DIR/clusters/${cluster}.sh" "$INSTALL_DIR/clusters/${cluster}.sh"
    done
else
    echo "Downloading configuration files..."
    curl -sSL "$GITHUB_BASE_URL/common.sh" -o "$INSTALL_DIR/common.sh"
    curl -sSL "$GITHUB_BASE_URL/update.sh" -o "$INSTALL_DIR/update.sh"
    chmod +x "$INSTALL_DIR/update.sh"
    for cluster in "${CLUSTERS[@]}"; do
        curl -sSL "$GITHUB_BASE_URL/clusters/${cluster}.sh" -o "$INSTALL_DIR/clusters/${cluster}.sh"
    done
fi

# Detect cluster from hostname
DETECTED_CLUSTER=""
CURRENT_HOSTNAME=$(hostname)

echo "Detecting cluster from hostname: $CURRENT_HOSTNAME"

for cluster in "${CLUSTERS[@]}"; do
    # Skip local - it's only used as fallback
    [ "$cluster" = "local" ] && continue

    # Extract the pattern from cluster config (read only the pattern line)
    PATTERN=$(grep "^CLUSTER_HOSTNAME_PATTERN=" "$INSTALL_DIR/clusters/${cluster}.sh" | cut -d'"' -f2)

    # Skip if pattern is empty or file was not downloaded correctly
    [ -z "$PATTERN" ] && continue

    if echo "$CURRENT_HOSTNAME" | grep -qE "$PATTERN"; then
        DETECTED_CLUSTER="$cluster"
        echo "Detected cluster: $DETECTED_CLUSTER"
        break
    fi
done

if [ -z "$DETECTED_CLUSTER" ]; then
    echo "Could not detect cluster from hostname '$CURRENT_HOSTNAME'"
    echo "Falling back to local mode"
    DETECTED_CLUSTER="local"
fi

# Generate config.sh
echo "Generating configuration for $DETECTED_CLUSTER..."
cat > "$INSTALL_DIR/config.sh" << EOF
# OpenEuroLLM environment configuration
# Generated by install.sh - do not edit manually
# Cluster: $DETECTED_CLUSTER

source "$INSTALL_DIR/clusters/${DETECTED_CLUSTER}.sh"
source "$INSTALL_DIR/common.sh"
EOF

# Add to shell rc files
SOURCE_LINE="source \"$INSTALL_DIR/config.sh\""

add_to_rc() {
    local rc_file="$1"
    if [ -f "$rc_file" ]; then
        if ! grep -qF "$INSTALL_DIR/config.sh" "$rc_file"; then
            echo "" >> "$rc_file"
            echo "# OpenEuroLLM cluster environment" >> "$rc_file"
            echo "$SOURCE_LINE" >> "$rc_file"
            echo "Added to $rc_file"
        else
            echo "Already present in $rc_file"
        fi
    fi
}

echo "Updating shell configuration..."
add_to_rc "$HOME/.bashrc"
add_to_rc "$HOME/.zshrc"

echo ""
echo "Installation complete!"
echo "Cluster: $DETECTED_CLUSTER"
echo "Config:  $INSTALL_DIR/config.sh"
echo ""

# Display environment variables
source "$INSTALL_DIR/config.sh"
echo "Environment variables set:"
echo "  OELLM_PROJECT_ROOT=$OELLM_PROJECT_ROOT"
echo "  OELLM_EVAL_DIR=$OELLM_EVAL_DIR"
echo "  OELLM_CONTAINERS_DIR=$OELLM_CONTAINERS_DIR"
echo "  OELLM_CHECKPOINTS_PRETRAIN_DIR=$OELLM_CHECKPOINTS_PRETRAIN_DIR"
echo "  OELLM_CHECKPOINTS_POSTTRAIN_DIR=$OELLM_CHECKPOINTS_POSTTRAIN_DIR"
echo "  OELLM_DATASETS_RAW_DIR=$OELLM_DATASETS_RAW_DIR"
echo "  OELLM_DATASETS_TOKENIZED_DIR=$OELLM_DATASETS_TOKENIZED_DIR"
echo "  HF_HOME=$HF_HOME"
echo "  OELLM_WANDB_DIR=$OELLM_WANDB_DIR"
echo "  WANDB_PROJECT=$WANDB_PROJECT"
echo "  OELLM_SLURM_JOBS_DIR=$OELLM_SLURM_JOBS_DIR"
echo "  OELLM_SLURM_DEFAULT_PARTITION=$OELLM_SLURM_DEFAULT_PARTITION"
echo "  OELLM_SLURM_DEFAULT_ACCOUNT=$OELLM_SLURM_DEFAULT_ACCOUNT"
echo ""
echo "To update later, run:"
echo "  $INSTALL_DIR/update.sh"
